from enum import Enum
class YoutubeUserID(Enum):
    HANGYEOL = 'UCluZa5CRH783-eU22_N7f7w'
    YEORUMI = 'UC9UBS38T2wKKbEKgPFdAoFQ'
    BEEMONG = 'UCnWEtTLqxplJccIRh3sFjJg'
    U32 =  'UCjsSt2r6DMjNlN6X4TjCc0g'
    ENYO = 'UCduZ7VkJD2_zWC_Sw61WzGA'
    CHARMANTE = 'UCiWqkt4_1wzWtvCuUAe0fTA'
    GODANSSI = 'UCCNIKF7tOs3aeYeFudkwFng'

class YoutubeReplayUserID(Enum):
    HANGYEOL = 'UC6forhu1WLjBfnsj5jGMTNg'
    YEORUMI = 'UC1i0ljmUYx1WaMkB11bV73A'
    BEEMONG = 'UC-PEEzHOQCgAA2X96WAndpg'
    U32 = 'UCTadusbDjUfO3KGFL3UEg_A'
    ENYO = 'UCquGeCHX1cuf1Gad7rsdNcA'
    CHARMANTE = 'UC-Q-L_gwoOYsppZ3d8z1uJA'
    GODANSSI = 'UCTQOk-T48mOz7-KE64ZFS5g'

class YoutubeClipUserID(Enum):
    HANGYEOL = 'UNDEFINED_HANGYEOL'
    YEORUMI = 'UCzAGJWuH3aUHPqjHpllJ5RA'
    BEEMONG = 'UNDEFINED_BEEMONG'
    U32 = 'UNDEFINED_U32'
    ENYO = 'UNDEFINED_ENYO'
    CHARMANTE = 'UNDEFINED_CHARMANTE'
    GODANSSI = 'UNDEFINED_GODANSSI'